### PR TITLE
Add the ability to inject a file to read from

### PR DESCRIPTION
**Pull request by brendandburns**
This is so that we can use this library elsewhere, where we may pass in a different stream.

### CODE REVIEW

**Comment by howeyc** [comment]
Sorry for not replying earlier....

But, if you are not reading from the terminal, why are you using this library?

**Comment by brendandburns** [comment]
@howeyc thanks for the response.  This is for injecting a reader so that I can validate via unit tests.

**Comment by shurcooL** [comment]
> This is for injecting a reader so that I can validate via unit tests.

In that case, it shouldn't add `SetReader` to the public API of this library for all users.

**Comment by brendandburns** [comment]
Given the way package protections in Go work I can't set the reader for tests from outside the `gopass` package, and I can't add my tests to the `gopass` package (since they'd then have to be in your repo, and they test more than just `gopass`)

I'm ok calling it something like `InjectReaderForTesting` if you'd rather.

--brendan

**Comment by shurcooL** [comment]
Oh, so you meant you want to use this for testing _your code_ that uses `gopass`, not for tests of `gopass` itself.

In that case, can your code use a wrapper around `gopass` that contains the `SetReader` you want, or one that can be swapped out by a mock for your tests?

If I understand correctly, this change is analogous to trying to add `SetReader` to `os` package so that `os.Open` would open the provided reader instead of a real file. That doesn't seem to be the concern of `os` package, it should be the using code providing a way to mock it out.

Do you have thoughts on that?

**Comment by brendandburns** [comment]
Yeah, I can do it that way, it's a little clunkier on my end since it requires plumbing a new interface down into my code to do the injection, I can do that.

I guess my feeling is that it's kind of dirty to code things in terms of a specific interface (e.g. `os.Stdin`) when you can instead code them in terms of a general interface (e.g. `io.Reader`) but I don't much care and it's your library (for which I'm grateful ;) so I will defer to your judgement.

Thanks for taking a look (and writing the library in the first place)
--brendan

**Comment by shurcooL** [comment]
Hey, you might've misunderstood, but I'm not the library author. I'm just a person who happens to write Go code and is [watching](https://github.com/howeyc/gopass/watchers) this Go library. I saw this issue and wanted to have a discussion that could potentially lead to a better outcome for this library's API.

I do think that if you're able to achieve the behavior and tests without adding specific support for that to `go-pass`, then it's likely a better outcome, since it leads to a smaller and easier to use API for the general audience. But that's just my observation and opinion, perhaps others would have different thoughts.

**Pull request closed without merging**
